# Generated by Django 4.2.2 on 2023-06-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=50)),
                ('seller_email', models.EmailField(max_length=254, unique=True)),
                ('seller_password', models.CharField(max_length=100)),
                ('seller_conformpassword', models.CharField(max_length=100)),
                ('seller_propic', models.FileField(default='defult.jpg', upload_to='media/')),
            ],
        ),
    ]
