# Generated by Django 4.2.2 on 2023-06-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_register',
            name='seller_propic',
            field=models.FileField(default='defult.jpg', upload_to='seller/'),
        ),
    ]
