# Generated by Django 4.2.2 on 2023-06-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0002_alter_seller_register_seller_propic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_register',
            name='seller_propic',
            field=models.FileField(default='seller/defult.jpg', upload_to='seller/'),
        ),
    ]
