# Generated by Django 4.2.2 on 2023-06-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0003_alter_seller_register_seller_propic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing_Catlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Catlog_Image', models.FileField(default='Listing/defult.jpg', upload_to='Listing/')),
                ('Catlog_Name', models.CharField(max_length=50)),
                ('Catlog_Price', models.CharField(max_length=50)),
                ('Catlog_Color', models.CharField(max_length=50)),
                ('Catlog_Fabric', models.CharField(max_length=50)),
                ('Catlog_Discription', models.CharField(max_length=500)),
            ],
        ),
    ]
