# Generated by Django 4.2.2 on 2023-06-30 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0004_listing_catlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing_catlog',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller_app.seller_register'),
        ),
    ]
