# Generated by Django 4.2.2 on 2023-07-04 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0006_listing_catlog_catlog_quntity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing_Catlog',
        ),
        migrations.DeleteModel(
            name='Seller_Register',
        ),
    ]
