# Generated by Django 4.2.2 on 2023-07-04 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller_app', '0007_delete_listing_catlog_delete_seller_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=50)),
                ('seller_email', models.EmailField(max_length=254, unique=True)),
                ('seller_password', models.CharField(max_length=100)),
                ('seller_conformpassword', models.CharField(max_length=100)),
                ('seller_propic', models.FileField(default='seller/defult.jpg', upload_to='seller/')),
            ],
        ),
        migrations.CreateModel(
            name='Listing_Catlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Catlog_Image', models.FileField(default='Listing/defult.jpg', upload_to='Listing/')),
                ('Catlog_Name', models.CharField(max_length=50)),
                ('Catlog_Price', models.IntegerField()),
                ('Catlog_Sale_Price', models.IntegerField()),
                ('Catlog_Quntity', models.IntegerField()),
                ('Catlog_Size', models.CharField(choices=[('XS', 'Xs'), ('S', 's'), ('M', 'm'), ('L', 'l'), ('XL', 'Xl'), ('XXL', 'Xxl'), ('XXXL', 'Xxxl')], default='XS', max_length=7)),
                ('Catlog_Color', models.CharField(max_length=50)),
                ('Catlog_Fabric', models.CharField(max_length=50)),
                ('Catlog_Discription', models.CharField(max_length=500, null=True)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller_app.seller_register')),
            ],
        ),
    ]
