# Generated by Django 4.2.2 on 2023-07-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing_catlog',
            name='Catlog_Sale_Price',
            field=models.IntegerField(null=True),
        ),
    ]
