# Generated by Django 4.2.2 on 2023-07-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0009_alter_listing_catlog_catlog_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing_catlog',
            name='Catlog_Size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='XS', max_length=100),
        ),
    ]
