# Generated by Django 4.2.2 on 2023-07-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0010_alter_listing_catlog_catlog_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing_catlog',
            name='Catlog_Size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=100),
        ),
    ]
