# Generated by Django 4.2.2 on 2023-07-05 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0011_alter_listing_catlog_catlog_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing_Catlog',
        ),
        migrations.DeleteModel(
            name='Seller_Register',
        ),
    ]
