# Generated by Django 4.2.2 on 2023-07-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0013_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing_catlog',
            name='Catlog_Color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Yellow', 'Yellow'), ('Blue', 'Blue'), ('Red', 'Red'), ('Green', 'Green')], max_length=100),
        ),
    ]
