# Generated by Django 4.2.2 on 2023-07-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0014_alter_listing_catlog_catlog_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing_catlog',
            name='Catlog_Price',
            field=models.IntegerField(default=0),
        ),
    ]
