# Generated by Django 4.2.2 on 2023-07-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0015_alter_listing_catlog_catlog_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing_catlog',
            name='Catlog_Catgary',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
