# Generated by Django 4.2.2 on 2023-07-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0016_listing_catlog_catlog_catgary'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing_catlog',
            name='Catlog_Branding',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing_catlog',
            name='Catlog_Tags',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
