# Generated by Django 4.2.2 on 2023-06-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_app', '0003_alter_register_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='propic',
            field=models.FileField(default='media/defualt_pic.jpg', upload_to='media/'),
        ),
    ]
