# Generated by Django 4.2.2 on 2023-06-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_app', '0004_register_propic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='propic',
            field=models.FileField(default='defualt_pic.jpg', upload_to='media/'),
        ),
    ]
