# Generated by Django 4.2.2 on 2023-06-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_app', '0005_alter_register_propic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='conformpassword',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='propic',
            field=models.FileField(default='defult.jpg', upload_to='media/'),
        ),
    ]
