# Generated by Django 4.2.2 on 2023-07-06 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0014_alter_listing_catlog_catlog_color'),
        ('fashion_app', '0006_alter_register_conformpassword_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashion_app.register')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller_app.listing_catlog')),
            ],
        ),
    ]
