# Generated by Django 4.2.2 on 2023-07-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_app', '0007_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
