# Generated by Django 4.2.2 on 2023-07-11 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_app', '0008_cart_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=25)),
                ('postcode', models.IntegerField(default=0)),
                ('phone', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=50)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashion_app.register')),
            ],
        ),
    ]
