# Generated by Django 4.2.2 on 2023-07-11 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_app', '0009_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Detailss',
        ),
    ]
