# Generated by Django 4.2.2 on 2023-07-11 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_app', '0010_rename_details_detailss'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detailss',
            new_name='Details',
        ),
    ]
