# Generated by Django 4.2.2 on 2023-07-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_app', '0013_details_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='order_id',
            field=models.CharField(max_length=20),
        ),
    ]
