# Generated by Django 4.2.2 on 2023-07-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_app', '0014_alter_details_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
