# Generated by Django 4.2.2 on 2023-07-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_app', '0016_cart_details_id_alter_details_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='stetus',
            field=models.BooleanField(default=True),
        ),
    ]
