# Generated by Django 4.2.2 on 2023-07-17 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_app', '0018_details_second_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_id',
        ),
    ]
