# Generated by Django 4.2.2 on 2023-07-17 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0016_listing_catlog_catlog_catgary'),
        ('fashion_app', '0019_remove_cart_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller_app.listing_catlog'),
        ),
    ]
